import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../context/AuthContext';
import { Award, ExternalLink } from 'lucide-react';

interface Certificate {
  id: number;
  certificate_code: string;
  issued_at: string;
  event_registrations: {
    assigned_role: string;
    events: {
      name: string;
      event_date: string;
    };
  };
}

export const StudentCertificates: React.FC = () => {
  const { profile } = useAuth();
  const [certificates, setCertificates] = useState<Certificate[]>([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchCertificates = async () => {
      if (!profile) return;
      setLoading(true);

      try {
        const { data, error } = await supabase
          .from('certificates')
          .select(`
            id,
            certificate_code,
            issued_at,
            event_registrations!inner (
              assigned_role,
              student_id,
              events!inner (
                name,
                event_date
              )
            )
          `)
          .eq('event_registrations.student_id', profile.id)
          .order('issued_at', { ascending: false });

        if (error) throw error;
        setCertificates((data as any) || []);
      } catch (err) {
        console.error('Error fetching certificates:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchCertificates();
  }, [profile]);

  const getRoleLabel = (role: string) => {
    switch (role) {
      case 'volunteers':
        return 'Volunteer';
      case 'OC':
        return 'Organizing Committee Member';
      case 'CC':
        return 'Co-coordinator';
      default:
        return 'Participant';
    }
  };

  if (loading) {
    return (
      <div className="container main-content" style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '60vh' }}>
        <p>Loading certificates...</p>
      </div>
    );
  }

  return (
    <div className="container main-content">
      <div className="hero" style={{ padding: '2rem 0' }}>
        <h1 className="hero-title" style={{ fontSize: '2.5rem' }}>My Academic Certificates</h1>
        <p className="hero-subtitle" style={{ fontSize: '1.1rem', margin: '0.5rem auto' }}>
          View and print your event activity certificates for MAR points.
        </p>
      </div>

      {certificates.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem' }}>
          <Award size={48} style={{ color: 'var(--text-muted)', marginBottom: '1rem' }} />
          <h3>No certificates issued yet.</h3>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>
            Certificates are generated by administrators after events are completed and attendance is verified.
          </p>
        </div>
      ) : (
        <div className="table-responsive show-alert-anim">
          <table className="table">
            <thead>
              <tr>
                <th>Event Name</th>
                <th>Role</th>
                <th>Issue Date</th>
                <th>Verification Code</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {certificates.map((cert) => (
                <tr key={cert.id}>
                  <td><strong>{cert.event_registrations.events.name}</strong></td>
                  <td>{getRoleLabel(cert.event_registrations.assigned_role)}</td>
                  <td>{new Date(cert.issued_at).toLocaleDateString()}</td>
                  <td style={{ fontFamily: 'monospace', fontWeight: 'bold' }}>{cert.certificate_code}</td>
                  <td>
                    <button
                      onClick={() => navigate(`/student/view-certificate/${cert.id}`)}
                      className="btn btn-primary btn-sm"
                      style={{ display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                    >
                      <ExternalLink size={14} /> View Certificate
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
